import { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Alert, Button, Card, Input } from '../../../components/ui'
import { useErrorHandler } from '../hooks/useErrorHandler'
import { authService } from '../services/authService'
import { passwordChecks, validatePassword, validatePasswordConfirmation } from '../utils/validators'

export default function ActivationTokenPage() {
  const [params] = useSearchParams(); const token = params.get('token') ?? ''
  const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState(''); const [done, setDone] = useState(false); const [loading, setLoading] = useState(false); const formatError = useErrorHandler()
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const validation = validatePassword(password) || validatePasswordConfirmation(password, confirmation); if (!token) return setError('El enlace no contiene un token válido'); if (validation) return setError(validation); setLoading(true); setError(''); try { await authService.activateAccount(token, password); setDone(true) } catch (cause) { setError(formatError(cause)) } finally { setLoading(false) } }
  return <main className="flex min-h-screen items-center justify-center bg-brand-sand/40 px-6 py-12"><Card className="w-full max-w-md p-7"><Link to="/usuarios/login" className="text-sm font-semibold text-brand-green-strong hover:underline">← Volver a iniciar sesión</Link><h1 className="mt-5 text-2xl font-bold text-brand-navy">Activar cuenta</h1>{done ? <div className="mt-6 space-y-4"><Alert variant="success" title="Cuenta activada">Ya puedes iniciar sesión con tu nueva contraseña.</Alert><Link to="/usuarios/login" className="block text-center font-semibold text-brand-green-strong hover:underline">Ir al inicio de sesión</Link></div> : <form onSubmit={submit} className="mt-7 space-y-5">{error && <Alert variant="error">{error}</Alert>}<div><label htmlFor="activate-password" className="mb-1.5 block text-sm font-semibold text-brand-navy">Crea tu contraseña</label><Input id="activate-password" type="password" autoComplete="new-password" value={password} onChange={(event: React.ChangeEvent<HTMLInputElement>) => setPassword(event.target.value)} /><ul className="mt-2 grid gap-1 text-xs text-brand-ink/65 sm:grid-cols-2">{passwordChecks(password).map((check) => <li key={check.label} className={check.valid ? 'text-brand-green-strong' : ''}>{check.valid ? '✓' : '•'} {check.label}</li>)}</ul></div><div><label htmlFor="activate-confirm" className="mb-1.5 block text-sm font-semibold text-brand-navy">Confirmar contraseña</label><Input id="activate-confirm" type="password" autoComplete="new-password" value={confirmation} onChange={(event: React.ChangeEvent<HTMLInputElement>) => setConfirmation(event.target.value)} /></div><Button type="submit" disabled={loading} className="w-full">{loading ? 'Activando...' : 'Activar cuenta'}</Button></form>}</Card></main>
}