import { Card } from '../../../../components/ui'
import { Link } from 'react-router-dom'
import { useUserProfile } from './hooks/useUserProfile'

export function UserProfile() {
  const { user } = useUserProfile()
  if (!user) return null
  const fullName = [user.person?.name, user.person?.first_lastname, user.person?.second_lastname].filter(Boolean).join(' ') || 'Sin nombre registrado'
  return <Card className="overflow-visible">
    <div className="flex flex-wrap items-center justify-between gap-6 bg-brand-navy px-7 py-8 text-white md:px-10 md:py-10"><div className="flex items-center gap-5"><div className="flex h-20 w-20 items-center justify-center rounded-full bg-brand-green text-3xl font-bold text-white ring-4 ring-white/15">{fullName.charAt(0)}</div><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-brand-yellow">Usuario registrado</p><h2 className="mt-2 text-2xl font-bold md:text-3xl">{fullName}</h2><p className="mt-1 text-sm text-white/70">{user.email}</p></div></div><div className="rounded-lg border border-white/15 px-5 py-3 text-sm text-white/75"><span className="block text-xs uppercase tracking-wide text-white/50">Rol</span><strong className="mt-1 block text-white">{user.role}</strong></div></div>
    <div className="grid gap-8 p-7 md:grid-cols-[1fr_0.8fr] md:p-10"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-brand-green-strong">Datos de contacto</p><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-lg border border-brand-navy/10 bg-brand-paper p-5 sm:col-span-2"><dt className="text-xs font-bold uppercase tracking-wide text-brand-ink/55">Correo electrónico</dt><dd className="mt-2 break-all text-lg font-semibold text-brand-navy">{user.email}</dd></div><div className="rounded-lg border border-brand-navy/10 bg-brand-paper p-5"><dt className="text-xs font-bold uppercase tracking-wide text-brand-ink/55">Nombre</dt><dd className="mt-2 text-brand-navy">{fullName}</dd></div><div className="rounded-lg border border-brand-navy/10 bg-brand-paper p-5"><dt className="text-xs font-bold uppercase tracking-wide text-brand-ink/55">Rol de cuenta</dt><dd className="mt-2 text-brand-navy">{user.role}</dd></div></dl></div><div className="flex flex-col justify-between rounded-xl border border-brand-navy/10 bg-brand-sand/45 p-6"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-brand-green-strong">Seguridad</p><h3 className="mt-3 text-xl font-bold text-brand-navy">Protege tu acceso</h3><p className="mt-2 text-sm leading-6 text-brand-ink/65">Actualiza tu contraseña periódicamente para mantener segura tu cuenta.</p></div><Link to="/usuarios/cambiar-contrasena" state={{ from: '/usuarios/perfil' }} className="mt-8 inline-flex cursor-pointer items-center justify-center gap-2 rounded-lg bg-brand-yellow px-7 py-3.5 text-sm font-semibold text-brand-navy transition-colors hover:brightness-95">Cambiar contraseña</Link></div></div>
  </Card>
}
